### ISSUE TITLE
browse-url of entry at point

### ISSUE THREAD

**Issue by mooseyboots** [progfolio/wikinfo#1]
hi, 
i'm wiki-summary and helm-wikipedia-suggest and just discovered this library. 

i wonder how one would go about hooking in `browse-url` to the entry list, which is displayed in the minibuffer, so it has no mode/keymap etc., afaict.

wikisummary also lacks this feature, but seeing as yours is more active i thought i'd ask here. it wd be nice to be able to plug them in together:

- select a candidate, display the fully summary text
- binding from that buffer to load full page with `browse-url`.

**Comment by mooseyboots** [comment]
ah, sorry for the bother, i guess it's only a matter of handling the plist returned and displaying the :wikinfo (:extract details?

but it looks like a test of what that returns gives 1/2 the text that wikisummary does.

```
(wikinfo "try" #'car)
```
returned The Try Guys [sorry for awful example], and the : wikinfo :extract is 

"The Try Guys is an American online entertainment group and media production company which produces content for their YouTube channel. The group was founded by Keith Habersberger, Ned Fulmer, Zach Kornfeld, and Eugene Lee Yang. The Try Guys are known for testing a wide range of activities, such as testing their sperm count, raising toddlers, shaving their legs, and wearing women's underwear."

wikisummary gives:

"The Try Guys is an American online entertainment group and media production
company which produces content for their YouTube channel. The group was
founded by Keith Habersberger, Ned Fulmer, Zach Kornfeld, and Eugene Lee Yang. The Try Guys are known for testing a wide range of activities, such as testing their sperm count, raising toddlers, shaving their legs, and wearing women's underwear. The four men created The Try Guys while working for BuzzFeed, before forming their own company, 2nd Try LLC, in 2018. They have since expanded their company to include more than twenty employees, starred in a show on the Food Network, and released a book titled The Hidden Power of
F*cking Up. Fulmer was removed from the company in September 2022 after it was revealed that he had engaged in an extramarital affair with an employee. As of October 2022, the channel hosts eleven spinoff series starring employees of
the company and other collaborators."

[not sure if a priority for yr package, but seems like a nice idea to me.

**Comment by mooseyboots** [comment]
i was looking at something like 

```
  (defun wikinfo-go (arg)
    (interactive "sWikinfo: ")
    (let* ((choice (wikinfo arg))
           (extract (plist-get 
                     (plist-get choice :wikinfo)
                     :extract)))
      (with-output-to-temp-buffer "*wikinfo-summary*"
        (prin1 extract)
    ;;  add a browse-url binding to local map here
        ))
```

**Comment by martianhi** [comment]
i worked something out by shelling out to wiki-summary:

```lisp
(defun wiki-summary-browse-current ()
    (interactive)
    (browse-url (concat "https://en.wikipedia.org/wiki/" wiki-summary-title)))
  (defun wikinfo-go (arg)
    (interactive "sWikinfo: ")
    (let* ((choice (wikinfo arg))
           (wikinfo (plist-get choice :wikinfo))
           (extract (plist-get wikinfo :extract))
           (title (plist-get wikinfo :title)))
      (wiki-summary title)
      (sleep-for 0.25) ; why is this needed?
      (with-current-buffer "*wiki-summary*"
        (setq-local wiki-summary-title title)
        (local-set-key (kbd "b") #'wiki-summary-browse-current))))
  (global-set-key (kbd "C-c w i") 'wikinfo-go)
```

this means you can seamlessly go from wikinfo, to wiki summary, to loading with browse-url.
